# Generated by Django 4.2.3 on 2023-07-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_embed", "0004_environment_host_jobtype_job_output_tool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="cores",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="host",
            name="memory",
            field=models.IntegerField(null=True),
        ),
    ]
